FROM cern/cs9-base:latest
MAINTAINER Ruslan Mashinistov "mashinistov@bnl.gov"

#install pip3
RUN yum install -y python3-pip
RUN yum install -y git
RUN yum install -y python3-psycopg2
RUN yum install -y postgresql-devel
RUN yum install -y python3-devel gcc
RUN yum install -y postgresql lsof

COPY . /nopayloaddb

RUN pip3 install -r /nopayloaddb/requirements.txt

RUN pip3 install gunicorn
RUN pip3 install pytz

RUN yum install -y sudo vim


RUN useradd docker
RUN echo "docker ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/docker
RUN chmod 0440 /etc/sudoers.d/docker
RUN usermod -aG wheel docker
RUN chown -R docker:docker /nopayloaddb
RUN chown -R docker:docker /var/log

USER docker

WORKDIR /nopayloaddb
CMD gunicorn \
  --graceful-timeout 1800 \
  --timeout 1800 \
  --workers 1 \
  --threads 4 \
  --access-logfile - \
  --error-logfile - \
  --log-level info \
  nopayloaddb.wsgi:application \
  --bind 0.0.0.0:8000 \
  2>&1 | tee /var/log/gunicorn.log
