# Generated by Django 3.2.9 on 2022-11-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdb_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltag',
            name='author',
            field=models.CharField(db_column='author', max_length=80, null=True),
        ),
    ]
