name: Documentation

on:
  - push

#  pull_request:
#  push:
#    branches:
#      - master

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

  # Build the documentation
      - name: Build the documentation
        run: |
          pip install -r requirements.txt
          cd docs
          make html