name: Build and Push Docker Image on Release

on:
  release:
    types: [published]  # Trigger only on new release

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo "GitHub release/tag: $GITHUB_REF_NAME"
        docker build . \
        --file Dockerfile \
        --tag my-image-name:${GITHUB_REF_NAME}
