name: Build and Push Docker Image on Release

on:  
  push:
    tags:
      - '*'   # triggers on any new tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - uses: actions/checkout@v4

      # 2️⃣ Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Build and push the Docker image
      - name: Build and push Docker image
        run: |
          echo "GitHub release/tag: $GITHUB_REF_NAME"
          docker build . \
            --file Dockerfile_prod \
            --tag ghcr.io/${{ github.repository_owner | lower  }}/nopayloaddb:${GITHUB_REF_NAME}
          docker push ghcr.io/${{ github.repository_owner | lower  }}/nopayloaddb:${GITHUB_REF_NAME}
